# Bot配置
bot.token=8225083954:AAGymegzlCKECIaqMxKyYqFzwiWWddbnmGg
bot.username=傻乎乎是卧底

# 管理员ID（多个用逗号分隔）
admin.ids=6906663525,646844463

# 游戏配置
game.max.players=12
game.min.players=3
game.speaking.time=120
game.voting.time=90
game.join.time=180
game.undercover.ratio=0.33

# 词库配置
words.file=words.txt
words.reload.interval=5